// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqIw8nPsv5hKYf6QD3htz2XP4IufUSBGo',
    appId: '1:899588442580:web:3e3bafd2036e5d35066e41',
    messagingSenderId: '899588442580',
    projectId: 'platformexam-a157e',
    authDomain: 'platformexam-a157e.firebaseapp.com',
    storageBucket: 'platformexam-a157e.firebasestorage.app',
    measurementId: 'G-2WG67FW7EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHz7_LzTr2kzbJfmYTkAHEnZHXxDUC0A',
    appId: '1:899588442580:android:7d14d1c426fc26ba066e41',
    messagingSenderId: '899588442580',
    projectId: 'platformexam-a157e',
    storageBucket: 'platformexam-a157e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnAqhEV3i3zN3ra8QA8N7Ud674mHbTxcM',
    appId: '1:899588442580:ios:d2defc7ca6d52418066e41',
    messagingSenderId: '899588442580',
    projectId: 'platformexam-a157e',
    storageBucket: 'platformexam-a157e.firebasestorage.app',
    iosBundleId: 'com.example.platformexamapp',
  );
}
