import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:hugeicons/hugeicons.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:path_provider/path_provider.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';

import 'package:platformexamapp/core/theme/app_colors.dart';
import 'package:platformexamapp/features/auth/data/models/user_data.dart';
import 'package:platformexamapp/features/profile/ui/widgets/user_avatar.dart';

class AdminAttendanceReportDialog extends StatefulWidget {
  const AdminAttendanceReportDialog({super.key});

  static Future<void> show(BuildContext context) {
    return showDialog(
      context: context,
      builder: (context) => Dialog(
        backgroundColor: Colors.transparent,
        insetPadding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 20.h),
        child: const AdminAttendanceReportDialog(),
      ),
    );
  }

  @override
  State<AdminAttendanceReportDialog> createState() =>
      _AdminAttendanceReportDialogState();
}

class _AdminAttendanceReportDialogState
    extends State<AdminAttendanceReportDialog> {
  final ScreenshotController _screenshotController = ScreenshotController();
  bool isExporting = false;

  Future<void> _shareToWhatsApp(
    double avgPct,
    double highestPct,
    double lowestPct,
    int totalCount,
  ) async {
    setState(() => isExporting = true);
    try {
      final image = await _screenshotController.capture();
      if (image != null) {
        final tempDir = await getTemporaryDirectory();
        final file = await File(
          '${tempDir.path}/Egtma3na_Attendance_Report_${DateTime.now().millisecondsSinceEpoch}.png',
        ).create();
        await file.writeAsBytes(image);

        final textMsg =
            "📋 Egtma3na Church Attendance Summary Report\n"
            "• Date: ${DateTime.now().year}-${DateTime.now().month}-${DateTime.now().day}\n"
            "• Total Members: $totalCount\n"
            "• Average Attendance: ${avgPct.toStringAsFixed(1)}%\n"
            "• Highest: ${highestPct.toStringAsFixed(0)}% | Lowest: ${lowestPct.toStringAsFixed(0)}%\n\n"
            "Generated by Egtma3na Platform";

        await Share.shareXFiles([XFile(file.path)], text: textMsg);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text("Error sharing report: $e"),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => isExporting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final now = DateTime.now();
    final dateStr =
        "${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}";

    return FutureBuilder<QuerySnapshot>(
      future: FirebaseFirestore.instance.collection("users").get(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Container(
            height: 200.h,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(20.r),
            ),
            child: const Center(
              child: CircularProgressIndicator(color: AppColors.primaryColor),
            ),
          );
        }

        final docs = snapshot.data?.docs ?? [];
        List<UserData> members = [];
        double sumPct = 0.0;
        double highestPct = 0.0;
        double lowestPct = 100.0;

        for (var doc in docs) {
          final user = UserData.fromJson(
            doc.data() as Map<String, dynamic>,
            doc.id,
          );
          members.add(user);

          final pct = user.attendancePercentage ?? 0.0;
          sumPct += pct;
          if (pct > highestPct) highestPct = pct;
          if (pct < lowestPct) lowestPct = pct;
        }

        if (members.isEmpty) lowestPct = 0.0;
        final avgPct = members.isNotEmpty ? (sumPct / members.length) : 0.0;

        return Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Printable Report Container
            Screenshot(
              controller: _screenshotController,
              child: Container(
                padding: EdgeInsets.all(16.r),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(24.r),
                  border: Border.all(
                    color: AppColors.primaryColor.withValues(alpha: 0.2),
                    width: 1.5,
                  ),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.15),
                      blurRadius: 20,
                      offset: const Offset(0, 8),
                    ),
                  ],
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    // Header: Church Logo + Title + Date
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Row(
                          children: [
                            Container(
                              padding: EdgeInsets.all(8.r),
                              decoration: const BoxDecoration(
                                color: AppColors.primaryColor,
                                shape: BoxShape.circle,
                              ),
                              child: Icon(
                                Icons.church_rounded,
                                color: Colors.white,
                                size: 20.r,
                              ),
                            ),
                            SizedBox(width: 10.w),
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  "Egtma3na • إجتماعنا",
                                  style: TextStyle(
                                    fontSize: 14.sp,
                                    fontWeight: FontWeight.bold,
                                    color: AppColors.primaryColor,
                                  ),
                                ),
                                Text(
                                  "Attendance Summary Report",
                                  style: TextStyle(
                                    fontSize: 10.sp,
                                    color: Colors.grey[600],
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                        Container(
                          padding: EdgeInsets.symmetric(
                            horizontal: 10.w,
                            vertical: 5.h,
                          ),
                          decoration: BoxDecoration(
                            color: AppColors.primaryColor.withValues(
                              alpha: 0.1,
                            ),
                            borderRadius: BorderRadius.circular(10.r),
                          ),
                          child: Text(
                            dateStr,
                            style: TextStyle(
                              fontSize: 11.sp,
                              fontWeight: FontWeight.bold,
                              color: AppColors.primaryColor,
                            ),
                          ),
                        ),
                      ],
                    ),

                    SizedBox(height: 14.h),
                    Divider(color: Colors.grey[200], height: 1),
                    SizedBox(height: 12.h),

                    // Members Attendance Table
                    ConstrainedBox(
                      constraints: BoxConstraints(maxHeight: 320.h),
                      child: SingleChildScrollView(
                        child: Table(
                          columnWidths: const {
                            0: FlexColumnWidth(2.5), // Member Name
                            1: FlexColumnWidth(1.2), // Att %
                            2: FlexColumnWidth(1.4), // Streak
                            3: FlexColumnWidth(1.8), // Status
                          },
                          defaultVerticalAlignment:
                              TableCellVerticalAlignment.middle,
                          children: [
                            // Table Header Row
                            TableRow(
                              decoration: BoxDecoration(
                                color: AppColors.primaryColor.withValues(
                                  alpha: 0.08,
                                ),
                                borderRadius: BorderRadius.circular(8.r),
                              ),
                              children: [
                                _buildTableCell("Member", isHeader: true),
                                _buildTableCell("Att %", isHeader: true),
                                _buildTableCell("Streak", isHeader: true),
                                _buildTableCell("Status", isHeader: true),
                              ],
                            ),
                            ...members.map((m) {
                              final pct = m.attendancePercentage ?? 0.0;
                              Color statusColor;
                              String statusText;

                              if (pct >= 75.0) {
                                statusColor = Colors.green;
                                statusText = "Excellent";
                              } else if (pct >= 50.0) {
                                statusColor = Colors.orange;
                                statusText = "Improve";
                              } else {
                                statusColor = Colors.red;
                                statusText = "Follow-up";
                              }

                              return TableRow(
                                children: [
                                  Padding(
                                    padding: EdgeInsets.symmetric(
                                      vertical: 6.h,
                                      horizontal: 4.w,
                                    ),
                                    child: Row(
                                      children: [
                                        UserAvatar(
                                          imageUrl: m.profileImage,
                                          radius: 12.r,
                                        ),
                                        SizedBox(width: 6.w),
                                        Expanded(
                                          child: Text(
                                            m.name ?? "Member",
                                            style: TextStyle(
                                              fontSize: 11.sp,
                                              fontWeight: FontWeight.bold,
                                              color: Colors.black87,
                                            ),
                                            maxLines: 1,
                                            overflow: TextOverflow.ellipsis,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  _buildTableCell("${pct.toStringAsFixed(0)}%"),
                                  _buildTableCell("${m.displayStreak} 🔥"),
                                  Padding(
                                    padding: EdgeInsets.symmetric(
                                      vertical: 6.h,
                                      horizontal: 4.w,
                                    ),
                                    child: Container(
                                      padding: EdgeInsets.symmetric(
                                        horizontal: 6.w,
                                        vertical: 3.h,
                                      ),
                                      decoration: BoxDecoration(
                                        color: statusColor.withValues(
                                          alpha: 0.12,
                                        ),
                                        borderRadius: BorderRadius.circular(
                                          6.r,
                                        ),
                                      ),
                                      child: Text(
                                        statusText,
                                        style: TextStyle(
                                          fontSize: 9.sp,
                                          color: statusColor,
                                          fontWeight: FontWeight.bold,
                                        ),
                                        textAlign: TextAlign.center,
                                      ),
                                    ),
                                  ),
                                ],
                              );
                            }),
                          ],
                        ),
                      ),
                    ),

                    SizedBox(height: 14.h),
                    Divider(color: Colors.grey[200], height: 1),
                    SizedBox(height: 10.h),

                    // Summary Stats Footer
                    Container(
                      padding: EdgeInsets.all(10.r),
                      decoration: BoxDecoration(
                        color: Colors.grey[50],
                        borderRadius: BorderRadius.circular(14.r),
                        border: Border.all(
                          color: Colors.grey.withValues(alpha: 0.15),
                        ),
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceAround,
                        children: [
                          _buildSummaryTile(
                            "Total Members",
                            "${members.length}",
                            Colors.blue,
                          ),
                          _buildSummaryTile(
                            "Avg Attendance",
                            "${avgPct.toStringAsFixed(1)}%",
                            AppColors.primaryColor,
                          ),
                          _buildSummaryTile(
                            "Highest",
                            "${highestPct.toStringAsFixed(0)}%",
                            Colors.green,
                          ),
                          _buildSummaryTile(
                            "Lowest",
                            "${lowestPct.toStringAsFixed(0)}%",
                            Colors.red,
                          ),
                        ],
                      ),
                    ),

                    SizedBox(height: 10.h),

                    // Branding Watermark
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.verified,
                          size: 12.r,
                          color: AppColors.primaryColor,
                        ),
                        SizedBox(width: 4.w),
                        Text(
                          "Generated by Egtma3na Platform",
                          style: TextStyle(
                            fontSize: 9.sp,
                            fontWeight: FontWeight.bold,
                            color: Colors.grey[600],
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),

            SizedBox(height: 16.h),

            // WhatsApp Share Button
            SizedBox(
              width: double.infinity,
              height: 48.h,
              child: ElevatedButton.icon(
                onPressed: isExporting
                    ? null
                    : () => _shareToWhatsApp(
                        avgPct,
                        highestPct,
                        lowestPct,
                        members.length,
                      ),
                icon: HugeIcon(
                  icon: HugeIcons.strokeRoundedShare01,
                  size: 18.r,
                  color: Colors.white,
                ),
                label: Text(
                  "share_to_whatsapp".tr(),
                  style: TextStyle(
                    fontSize: 15.sp,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF25D366),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(14.r),
                  ),
                  elevation: 2,
                ),
              ),
            ),
          ],
        );
      },
    );
  }

  Widget _buildTableCell(String text, {bool isHeader = false}) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 6.h, horizontal: 4.w),
      child: Text(
        text,
        style: TextStyle(
          fontSize: isHeader ? 10.sp : 11.sp,
          fontWeight: isHeader ? FontWeight.bold : FontWeight.w600,
          color: isHeader ? AppColors.primaryColor : Colors.black87,
        ),
        textAlign: TextAlign.center,
      ),
    );
  }

  Widget _buildSummaryTile(String label, String value, Color color) {
    return Column(
      children: [
        Text(
          label,
          style: TextStyle(fontSize: 9.sp, color: Colors.grey[600]),
        ),
        SizedBox(height: 2.h),
        Text(
          value,
          style: TextStyle(
            fontSize: 12.sp,
            fontWeight: FontWeight.bold,
            color: color,
          ),
        ),
      ],
    );
  }
}
